// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/image.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessImageRequest) Reset() {
	*x = ProcessImageRequest{}
	mi := &file_proto_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessImageRequest) ProtoMessage() {}

func (x *ProcessImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessImageRequest.ProtoReflect.Descriptor instead.
func (*ProcessImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ProcessImageRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type ProcessImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessImageResponse) Reset() {
	*x = ProcessImageResponse{}
	mi := &file_proto_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessImageResponse) ProtoMessage() {}

func (x *ProcessImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessImageResponse.ProtoReflect.Descriptor instead.
func (*ProcessImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessImageResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ProcessImageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessImageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_image_proto protoreflect.FileDescriptor

const file_proto_image_proto_rawDesc = "" +
	"\n" +
	"\x11proto/image.proto\x12\x05image\"R\n" +
	"\x13ProcessImageRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\"e\n" +
	"\x14ProcessImageResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2W\n" +
	"\fImageService\x12G\n" +
	"\fProcessImage\x12\x1a.image.ProcessImageRequest\x1a\x1b.image.ProcessImageResponseB2Z0github.com/christheoreo/photo-k8-app/image/protob\x06proto3"

var (
	file_proto_image_proto_rawDescOnce sync.Once
	file_proto_image_proto_rawDescData []byte
)

func file_proto_image_proto_rawDescGZIP() []byte {
	file_proto_image_proto_rawDescOnce.Do(func() {
		file_proto_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_image_proto_rawDesc), len(file_proto_image_proto_rawDesc)))
	})
	return file_proto_image_proto_rawDescData
}

var file_proto_image_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_image_proto_goTypes = []any{
	(*ProcessImageRequest)(nil),  // 0: image.ProcessImageRequest
	(*ProcessImageResponse)(nil), // 1: image.ProcessImageResponse
}
var file_proto_image_proto_depIdxs = []int32{
	0, // 0: image.ImageService.ProcessImage:input_type -> image.ProcessImageRequest
	1, // 1: image.ImageService.ProcessImage:output_type -> image.ProcessImageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_image_proto_init() }
func file_proto_image_proto_init() {
	if File_proto_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_image_proto_rawDesc), len(file_proto_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_image_proto_goTypes,
		DependencyIndexes: file_proto_image_proto_depIdxs,
		MessageInfos:      file_proto_image_proto_msgTypes,
	}.Build()
	File_proto_image_proto = out.File
	file_proto_image_proto_goTypes = nil
	file_proto_image_proto_depIdxs = nil
}
