apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: photo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/christheoreo/photo-k8-app/api:f12d72a255c35c5588ccade470ae1daee677a310
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: database-url
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: photo-app
spec:
  selector:
    app: api
  ports:
  - port: 3000
    targetPort: 3000