apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: photo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/christheoreo/photo-k8-app/frontend:2ac212011a9c75c3dea4671fc533a65fdccd36c6
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: photo-app
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80