apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-worker
  namespace: photo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-worker
  template:
    metadata:
      labels:
        app: image-worker
    spec:
      containers:
      - name: image-worker
        image: ghcr.io/christheoreo/photo-k8-app/image-worker:e4d2bf468850cded7d50b352f9ed8048f47a7a81
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: image-secret
              key: database-url
        - name: VALKEY_HOST
          value: "valkey"
        - name: VALKEY_PORT
          value: "6379"