FROM golang:1.25-alpine

# Install protoc and build tools
RUN apk add --no-cache git

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy everything else
COPY . .


CMD ["go", "run", "main.go"]